name: liveid
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - scikit-learn=1.6.1
  - joblib=1.4.2
  - jupyter
  - ipython
  - tqdm=4.67.1
  - pip
  - h5py=3.12.1
  - gensim=4.3.3
  - pytorch=2.5.1
  - torchvision=0.20.1
  - scipy=1.13.1
  - networkx=3.2.1
  - pillow=11.1.0
  - requests=2.32.3
  - pyyaml=6.0.2
  - pyproj=3.6.1
  - shapely=2.0.7
  - cartopy=0.23.0
  - tensorflow=2.18.1
  - xgboost=2.1.4
  - pip:
      - wordcloud==1.9.4
      - plotly==6.0.1
      - smart-open==7.1.0
      - selenium==4.30.0
      - webdriver-manager==4.0.2
      - beautifulsoup4==4.13.3
      - fitsne==1.2.1
      - hmmlearn==0.3.3
      - python-dotenv==1.1.0
